import TaskBoard from "@/components/blocks/TaskBoard"
import MainLayout from "@/components/wrapper/MainLayout"
import { Box, Heading } from "@chakra-ui/react"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Box mb={4}>
          <Heading as="h1" size="lg" fontWeight="bold">
            Task Management
          </Heading>
        </Box>
        <TaskBoard />
      </MainLayout>
    </>
  )
}
